### ISSUE TITLE
Edit titles by pressing TAB after hotkey

### ISSUE THREAD

**Issue by henriquearthur** [dingo-d/CSS-Table-of-Contents#1]
It is nice to write the title and then press the respective hotkey to create the (sub)section. But sometimes I get confused, so I think it would be a good option that **if the user press the hotkey without having written anything before, the title should be selected, so the user can delete it and write the title he wants**.

Very nice plugin for those that like organization like me. Thanks. :)

**Comment by dingo-d** [comment]
Oh this is a good suggestion! I'll look into it. I'm currently working on some bugs, and adding some new implementations (like toggling between the sections).

The selection of the default text seems like a great addition. Thanks for the suggestion.

**Comment by dingo-d** [comment]
I released a new version with a few fixes and changes, it will probably take a few hours for package control to recrawl the repo for the new version to be updated. I added the selection of the text :) Thanks for the suggestion.
