### ISSUE TITLE
For Cud

### ISSUE THREAD

**Issue by Alexey-T** [dingo-d/CSS-Table-of-Contents#2]
Hi Denis
Maybe possible to 'port' plugin to CudaText?

**Comment by dingo-d** [comment]
I have never worked on CudaText, I don't know in what language are plugins for CudaText written. If it's python, then it wouldn't be much of a problem to do that :) 

If you have the knowledge, feel free to fork it and adapt it for CudaText :)

**Comment by Alexey-T** [comment]
It is python. I need some help: can you refactor? so that ST3-calls - in plugin; but all CSS work -in separate module css_work.py. So ST3 plugin calls

```
from .css_work import *
..
```

**Comment by dingo-d** [comment]
I don't know what changes I'd need to do for it to work with ST3, I was following the official guidelines when creating it, and I wouldn't like for it to break. I'll look into it when I find more time.

**Comment by Alexey-T** [comment]
I want to clarify. I need refactor of py code.

1) e.g. CsstocCreateSectionCommand

U have here

```
        if len(selected) == 0:
            if len(line) == 0:
                text = 'Section'
            else:
                text = line
        else:
            text = selected

        # Numbers check

        section_pat = '^(\/\*\*\*\*\*\*\*\*\*\*\*\*\*\*\* \d+)'
        section = re.findall(section_pat, contents, re.MULTILINE|re.DOTALL)

        if section:
            section_no = int(re.findall('(\d+)',section[len(section)-1])[0])
        else:
            section_no = 0

        section_no += 1
```

this part- above- can u write it to new file css_work.py? In `def css_toc_calc_section()` ? 
If u do, then I take this file- css_work.py- and call this def.
Cudatext plugin (my) and ST3 plugin- will use same file.

**Comment by Alexey-T** [comment]
2) CsstocCreateSubsectionCommand
At here, can u create (in this new py file) `def css_toc_calc_subsection()` which gets 
(section_n, subsection_n) ? Or gets text (which plugin inserts)

**Comment by dingo-d** [comment]
Hmmm, can't you just fork the plugin and make the changes? Would be much easier, since I'm currently swamped with other projects, plus I was working on an update of plugin, and I don't want to break the functionality of it :\

**Comment by Alexey-T** [comment]
Yes i can do changes: but can you, pls, use this change, so future update will update my py file?
(I can wait until you make upd)

**Comment by dingo-d** [comment]
Ok, I'll try to incorporate your changes in the future update.

**Comment by Alexey-T** [comment]
Posted a pull-req.

**Comment by dingo-d** [comment]
I saw it, and I think there shouldn't be any issues in merging this, I just want to test it first to see if everything will work. I'll probably test this during the weekend, hope you're not in a hurry. Thanks for the contribution :)

**Comment by Alexey-T** [comment]
I tested this code: all 4 commands :)

**Comment by dingo-d** [comment]
I've merged your PR, thank you for the contribution :)
