### ISSUE TITLE
Src: dupl constants

### ISSUE THREAD

**Issue by CudaText-addons** [dingo-d/CSS-Table-of-Contents#4]
Src has duplicate strs like:

`'/*************** '`
and others (closing, opening items)
Can u make

```
PREFIX_SECTION = '/*************** '
SUFFIX_SECTION
PREFIX_SUB_SECTION
etc
```

**Comment by dingo-d** [comment]
Do you mean should I make them constants and use them as such through the file? Sure, don't think that should be a problem :)

**Comment by Alexey-T** [comment]
Yes, these strs should be constants, str's should be appeared once

**Comment by dingo-d** [comment]
I've changed them on my local development version, when I'm done with updates I'll make a push here on git :)
