### ISSUE TITLE
Api: get TOC line cnt

### ISSUE THREAD

**Issue by Alexey-T** [dingo-d/CSS-Table-of-Contents#8]
Cud version https://github.com/CudaText-addons/cuda_css_toc
 what API exists to get lines count in TOC (toc is inserted)?
can u add `def get_toc_current_line_count(contents)`.
I want to del old TOC (need api) and ins new TOC (can do)

**Comment by dingo-d** [comment]
I will see about adding that when I find the time. I'm not 100% sure about what you need - a function that will add the line where TOC starts? In the new version if you have created TOC, then added some new sections, and if you re create TOC again it will just overwrite the existing one.

**Comment by Alexey-T** [comment]
TOC starts at line 0, ends at line N. I need to get N. e.g.
~~~
/*
TOC
dd
dd
*/
~~~
here N=4. Cudatext plugin knows N=4 and it dels then first N+1 lines.
