### ISSUE TITLE
Api: get pos of section name

### ISSUE THREAD

**Issue by Alexey-T** [dingo-d/CSS-Table-of-Contents#9]
Pls return not str, but `(str, pos_begin, pos_end)` for making section. and i can select substring- from pos_begin to pos_end. (pos_ is offset in resulting str).

**Comment by dingo-d** [comment]
That would require rewriting the defining commands for sections. Why would you need that?

**Comment by Alexey-T** [comment]
I need to select section title after ins to editor. e.g. "Name" in `/******* 2. Name ******/`

**Comment by Alexey-T** [comment]
it is for Cudatext plugin. it wants to select "Name here" in `/****** 1. Name here ******/`. wish: your API returns offset of title begin and title end. (title is "Name here"). e.g. 10 and 18.

**Comment by dingo-d** [comment]
I merged your PR. I think we can close this :) Thanks
